# Generated by Django 4.2.7 on 2026-05-02 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.CharField(choices=[('math', 'Математика'), ('physics', 'Физика'), ('chemistry', 'Химия'), ('biology', 'Биология'), ('geography', 'География'), ('history', 'История'), ('logic', 'Логика'), ('language', 'Русский язык')], max_length=30, verbose_name='Категория')),
                ('difficulty', models.CharField(choices=[('easy', 'Лёгкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='medium', max_length=20, verbose_name='Сложность')),
                ('game_type', models.CharField(choices=[('quiz', 'Викторина'), ('puzzle', 'Головоломка'), ('memory', 'Память'), ('typing', 'Набор текста'), ('math_race', 'Математическая гонка'), ('word', 'Слова')], max_length=30, verbose_name='Тип игры')),
                ('cover_url', models.URLField(verbose_name='Обложка')),
                ('xp_reward', models.IntegerField(default=50, verbose_name='Награда XP')),
                ('play_time', models.IntegerField(default=5, verbose_name='Время (мин)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('plays_count', models.IntegerField(default=0, verbose_name='Сыграно раз')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Вопрос')),
                ('option_a', models.CharField(max_length=300, verbose_name='Вариант А')),
                ('option_b', models.CharField(max_length=300, verbose_name='Вариант Б')),
                ('option_c', models.CharField(max_length=300, verbose_name='Вариант В')),
                ('option_d', models.CharField(max_length=300, verbose_name='Вариант Г')),
                ('correct', models.CharField(choices=[('a', 'А'), ('b', 'Б'), ('c', 'В'), ('d', 'Г')], max_length=1, verbose_name='Правильный ответ')),
                ('explanation', models.TextField(blank=True, verbose_name='Объяснение')),
                ('order', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='games.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0, verbose_name='Очки')),
                ('max_score', models.IntegerField(default=100, verbose_name='Макс. очки')),
                ('correct_answers', models.IntegerField(default=0, verbose_name='Правильных ответов')),
                ('total_questions', models.IntegerField(default=0, verbose_name='Всего вопросов')),
                ('time_spent', models.IntegerField(default=0, verbose_name='Время (сек)')),
                ('xp_earned', models.IntegerField(default=0, verbose_name='XP получено')),
                ('played_at', models.DateTimeField(auto_now_add=True, verbose_name='Сыграно')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='games.game', verbose_name='Игра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_results', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Результат игры',
                'verbose_name_plural': 'Результаты игр',
                'ordering': ['-played_at'],
            },
        ),
    ]
